timeout: 0
default_entry: MyOS tests

/MyOS
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=normal myos.loglevel=normal
    module_path: boot():/boot/initramfs.cpio
    module_string: initramfs

/MyOS verbose
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=normal myos.loglevel=verbose
    module_path: boot():/boot/initramfs.cpio
    module_string: initramfs

/MyOS debug
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=normal myos.loglevel=debug
    module_path: boot():/boot/initramfs.cpio
    module_string: initramfs

/MyOS tests
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=test myos.loglevel=verbose
    module_path: boot():/boot/initramfs.cpio
    module_string: initramfs
