timeout: 0
default_entry: MyOS tests

#${MYOS_RESOLUTION}=1024x768x32

/MyOS
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=normal myos.loglevel=normal
    #resolution: ${MYOS_RESOLUTION}

/MyOS verbose
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=normal myos.loglevel=verbose
    #resolution: ${MYOS_RESOLUTION}

/MyOS debug
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=normal myos.loglevel=debug
    #resolution: ${MYOS_RESOLUTION}

/MyOS tests
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=test myos.loglevel=verbose
    #resolution: ${MYOS_RESOLUTION}
