timeout: 0
default_entry: MyOS tests

/MyOS
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=normal myos.loglevel=normal
    resolution: 1920x1200x32

/MyOS verbose
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=normal myos.loglevel=verbose
    resolution: 1920x1200x32

/MyOS debug
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=normal myos.loglevel=debug
    resolution: 1920x1200x32

/MyOS tests
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: myos.boot=test myos.loglevel=verbose
    resolution: 1920x1200x32
