# -----------------------------------------------------------------------------
# Userspace test images
# -----------------------------------------------------------------------------

USER_TEST_BUILD_DIR := $(BUILD_DIR)/user-tests
TEST_SYSCALL_NUMBERS_HEADER := kernel/syscall/test_numbers.h

ELF_ENTRY_SOURCE        := user/tests/elf_entry.S
ELF_ENTRY_LINKER_SCRIPT := user/tests/elf_entry.ld
ELF_ENTRY_OBJECT        := $(USER_TEST_BUILD_DIR)/elf_entry.o
ELF_ENTRY_ELF           := $(USER_TEST_BUILD_DIR)/elf_entry.elf

ELF_FROM_VFS_SOURCE := user/tests/elf_from_vfs.S
ELF_FROM_VFS_OBJECT := $(USER_TEST_BUILD_DIR)/elf_from_vfs.o
ELF_FROM_VFS_ELF    := $(USER_TEST_BUILD_DIR)/elf_from_vfs.elf

SYSCALL_ABI_SOURCE := user/tests/syscall_abi.S
SYSCALL_ABI_OBJECT := $(USER_TEST_BUILD_DIR)/syscall_abi.o
SYSCALL_ABI_ELF    := $(USER_TEST_BUILD_DIR)/syscall_abi.elf

SYSCALL_POINTER_SOURCE := user/tests/syscall_pointer.S
SYSCALL_POINTER_OBJECT := $(USER_TEST_BUILD_DIR)/syscall_pointer.o
SYSCALL_POINTER_ELF    := $(USER_TEST_BUILD_DIR)/syscall_pointer.elf

FD_SYSCALLS_SOURCE := user/tests/fd_syscalls.S
FD_SYSCALLS_OBJECT := $(USER_TEST_BUILD_DIR)/fd_syscalls.o
FD_SYSCALLS_ELF    := $(USER_TEST_BUILD_DIR)/fd_syscalls.elf

SCHEDULER_CONTEXT_SOURCE := user/tests/scheduler_context.S
SCHEDULER_CONTEXT_OBJECT := $(USER_TEST_BUILD_DIR)/scheduler_context.o
SCHEDULER_CONTEXT_ELF    := $(USER_TEST_BUILD_DIR)/scheduler_context.elf

EXEC_CALLER_SOURCE := user/tests/exec_caller.S
EXEC_CALLER_OBJECT := $(USER_TEST_BUILD_DIR)/exec_caller.o
EXEC_CALLER_ELF    := $(USER_TEST_BUILD_DIR)/exec_caller.elf

EXEC_TARGET_SOURCE := user/tests/exec_target.S
EXEC_TARGET_OBJECT := $(USER_TEST_BUILD_DIR)/exec_target.o
EXEC_TARGET_ELF    := $(USER_TEST_BUILD_DIR)/exec_target.elf

WAITPID_PARENT_SOURCE := user/tests/waitpid_parent.S
WAITPID_PARENT_OBJECT := $(USER_TEST_BUILD_DIR)/waitpid_parent.o
WAITPID_PARENT_ELF    := $(USER_TEST_BUILD_DIR)/waitpid_parent.elf

WAITPID_CHILD_SOURCE := user/tests/waitpid_child.S
WAITPID_CHILD_OBJECT := $(USER_TEST_BUILD_DIR)/waitpid_child.o
WAITPID_CHILD_ELF    := $(USER_TEST_BUILD_DIR)/waitpid_child.elf

FORK_SOURCE := user/tests/fork.S
FORK_OBJECT := $(USER_TEST_BUILD_DIR)/fork.o
FORK_ELF    := $(USER_TEST_BUILD_DIR)/fork.elf

ELF_SELF_MODIFY_SOURCE := user/tests/elf_self_modify.S
ELF_SELF_MODIFY_OBJECT := $(USER_TEST_BUILD_DIR)/elf_self_modify.o
ELF_SELF_MODIFY_ELF    := $(USER_TEST_BUILD_DIR)/elf_self_modify.elf

ELF_ISOLATION_ATTACKER_SOURCE := user/tests/elf_isolation_attacker.S
ELF_ISOLATION_ATTACKER_OBJECT := $(USER_TEST_BUILD_DIR)/elf_isolation_attacker.o
ELF_ISOLATION_ATTACKER_ELF    := $(USER_TEST_BUILD_DIR)/elf_isolation_attacker.elf
ELF_ISOLATION_ATTACKER_LINKER_SCRIPT := user/tests/elf_isolation_attacker.ld

ELF_ISOLATION_VICTIM_SOURCE := user/tests/elf_isolation_victim.S
ELF_ISOLATION_VICTIM_OBJECT := $(USER_TEST_BUILD_DIR)/elf_isolation_victim.o
ELF_ISOLATION_VICTIM_ELF    := $(USER_TEST_BUILD_DIR)/elf_isolation_victim.elf

RUNTIME_STRING_SOURCE := user/tests/runtime_string.c
RUNTIME_STRING_OBJECT := $(USER_TEST_BUILD_DIR)/runtime_string.o
RUNTIME_STRING_ELF    := $(USER_TEST_BUILD_DIR)/runtime_string.elf

RUNTIME_MALLOC_SOURCE := user/tests/runtime_malloc.c
RUNTIME_MALLOC_OBJECT := $(USER_TEST_BUILD_DIR)/runtime_malloc.o
RUNTIME_MALLOC_ELF    := $(USER_TEST_BUILD_DIR)/runtime_malloc.elf

RUNTIME_STDIO_SOURCE := user/tests/runtime_stdio.c
RUNTIME_STDIO_OBJECT := $(USER_TEST_BUILD_DIR)/runtime_stdio.o
RUNTIME_STDIO_ELF    := $(USER_TEST_BUILD_DIR)/runtime_stdio.elf

RUNTIME_SYSCALLS_SOURCE := user/tests/runtime_syscalls.c
RUNTIME_SYSCALLS_OBJECT := $(USER_TEST_BUILD_DIR)/runtime_syscalls.o
RUNTIME_SYSCALLS_ELF    := $(USER_TEST_BUILD_DIR)/runtime_syscalls.elf

ELF_ENTRY_CFLAGS := \
	--target=$(TARGET) \
	-ffreestanding \
	-fno-stack-protector \
	-fno-common \
	-mno-red-zone \
	-mgeneral-regs-only \
	-O0 \
	-g

$(USER_TEST_BUILD_DIR):
	mkdir -p $(USER_TEST_BUILD_DIR)

$(ELF_ENTRY_OBJECT): $(ELF_ENTRY_SOURCE) | $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(ELF_ENTRY_ELF): $(ELF_ENTRY_OBJECT) $(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(ELF_ENTRY_OBJECT)

$(ELF_FROM_VFS_OBJECT): \
	$(ELF_FROM_VFS_SOURCE) \
	| $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(ELF_FROM_VFS_ELF): \
	$(ELF_FROM_VFS_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(ELF_FROM_VFS_OBJECT)

$(SYSCALL_ABI_OBJECT): $(SYSCALL_ABI_SOURCE) | $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(SYSCALL_ABI_ELF): \
	$(SYSCALL_ABI_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(SYSCALL_ABI_OBJECT)

$(SYSCALL_POINTER_OBJECT): $(SYSCALL_POINTER_SOURCE) | $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(SYSCALL_POINTER_ELF): \
	$(SYSCALL_POINTER_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(SYSCALL_POINTER_OBJECT)

$(FD_SYSCALLS_OBJECT): $(FD_SYSCALLS_SOURCE) | $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(FD_SYSCALLS_ELF): \
	$(FD_SYSCALLS_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(FD_SYSCALLS_OBJECT)

$(SCHEDULER_CONTEXT_OBJECT): \
	$(SCHEDULER_CONTEXT_SOURCE) \
	$(TEST_SYSCALL_NUMBERS_HEADER) \
	| $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(SCHEDULER_CONTEXT_ELF): \
	$(SCHEDULER_CONTEXT_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(SCHEDULER_CONTEXT_OBJECT)

$(EXEC_CALLER_OBJECT): \
	$(EXEC_CALLER_SOURCE) \
	$(TEST_SYSCALL_NUMBERS_HEADER) \
	| $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(EXEC_CALLER_ELF): \
	$(EXEC_CALLER_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(EXEC_CALLER_OBJECT)

$(EXEC_TARGET_OBJECT): $(EXEC_TARGET_SOURCE) | $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(EXEC_TARGET_ELF): \
	$(EXEC_TARGET_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(EXEC_TARGET_OBJECT)

$(WAITPID_PARENT_OBJECT): $(WAITPID_PARENT_SOURCE) | $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(WAITPID_PARENT_ELF): \
	$(WAITPID_PARENT_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(WAITPID_PARENT_OBJECT)

$(WAITPID_CHILD_OBJECT): $(WAITPID_CHILD_SOURCE) | $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(WAITPID_CHILD_ELF): \
	$(WAITPID_CHILD_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(WAITPID_CHILD_OBJECT)

$(FORK_OBJECT): $(FORK_SOURCE) | $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(FORK_ELF): \
	$(FORK_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(FORK_OBJECT)

$(ELF_SELF_MODIFY_OBJECT): \
	$(ELF_SELF_MODIFY_SOURCE) \
	| $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(ELF_SELF_MODIFY_ELF): \
	$(ELF_SELF_MODIFY_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(ELF_SELF_MODIFY_OBJECT)

$(ELF_ISOLATION_ATTACKER_OBJECT): \
	$(ELF_ISOLATION_ATTACKER_SOURCE) \
	| $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(ELF_ISOLATION_ATTACKER_ELF): \
	$(ELF_ISOLATION_ATTACKER_OBJECT) \
	$(ELF_ISOLATION_ATTACKER_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ISOLATION_ATTACKER_LINKER_SCRIPT) \
		-o $@ \
		$(ELF_ISOLATION_ATTACKER_OBJECT)

$(ELF_ISOLATION_VICTIM_OBJECT): \
	$(ELF_ISOLATION_VICTIM_SOURCE) \
	| $(USER_TEST_BUILD_DIR)
	$(CLANG) $(ELF_ENTRY_CFLAGS) \
		-c $< \
		-o $@

$(ELF_ISOLATION_VICTIM_ELF): \
	$(ELF_ISOLATION_VICTIM_OBJECT) \
	$(ELF_ENTRY_LINKER_SCRIPT)
	$(LD_LLD) \
		-T $(ELF_ENTRY_LINKER_SCRIPT) \
		-o $@ \
		$(ELF_ISOLATION_VICTIM_OBJECT)

$(RUNTIME_STRING_OBJECT): \
	$(RUNTIME_STRING_SOURCE) \
	$(USER_BOOTSTRAP_STRING_HEADER) \
	| $(USER_TEST_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(RUNTIME_STRING_ELF): \
	$(USER_BOOTSTRAP_RUNTIME_OBJECTS) \
	$(RUNTIME_STRING_OBJECT) \
	$(USER_BOOTSTRAP_LINKER_SCRIPT)
	$(LD_LLD) \
		-static \
		--build-id=none \
		-T $(USER_BOOTSTRAP_LINKER_SCRIPT) \
		-o $@ \
		$(USER_BOOTSTRAP_RUNTIME_OBJECTS) \
		$(RUNTIME_STRING_OBJECT)

$(RUNTIME_MALLOC_OBJECT): \
	$(RUNTIME_MALLOC_SOURCE) \
	$(USER_BOOTSTRAP_STDLIB_HEADER) \
	$(USER_BOOTSTRAP_STRING_HEADER) \
	| $(USER_TEST_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(RUNTIME_MALLOC_ELF): \
	$(USER_BOOTSTRAP_RUNTIME_OBJECTS) \
	$(RUNTIME_MALLOC_OBJECT) \
	$(USER_BOOTSTRAP_LINKER_SCRIPT)
	$(LD_LLD) \
		-static \
		--build-id=none \
		-T $(USER_BOOTSTRAP_LINKER_SCRIPT) \
		-o $@ \
		$(USER_BOOTSTRAP_RUNTIME_OBJECTS) \
		$(RUNTIME_MALLOC_OBJECT)

$(RUNTIME_STDIO_OBJECT): \
	$(RUNTIME_STDIO_SOURCE) \
	$(USER_BOOTSTRAP_STDIO_HEADER) \
	$(USER_BOOTSTRAP_STRING_HEADER) \
	| $(USER_TEST_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(RUNTIME_STDIO_ELF): \
	$(USER_BOOTSTRAP_RUNTIME_OBJECTS) \
	$(RUNTIME_STDIO_OBJECT) \
	$(USER_BOOTSTRAP_LINKER_SCRIPT)
	$(LD_LLD) \
		-static \
		--build-id=none \
		-T $(USER_BOOTSTRAP_LINKER_SCRIPT) \
		-o $@ \
		$(USER_BOOTSTRAP_RUNTIME_OBJECTS) \
		$(RUNTIME_STDIO_OBJECT)

$(RUNTIME_SYSCALLS_OBJECT): \
	$(RUNTIME_SYSCALLS_SOURCE) \
	$(USER_BOOTSTRAP_PROCESS_HEADER) \
	$(USER_BOOTSTRAP_FILE_HEADER) \
	$(USER_SYSCALL_ABI_HEADER) \
	| $(USER_TEST_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(RUNTIME_SYSCALLS_ELF): \
	$(USER_BOOTSTRAP_RUNTIME_OBJECTS) \
	$(RUNTIME_SYSCALLS_OBJECT) \
	$(USER_BOOTSTRAP_LINKER_SCRIPT)
	$(LD_LLD) \
		-static \
		--build-id=none \
		-T $(USER_BOOTSTRAP_LINKER_SCRIPT) \
		-o $@ \
		$(USER_BOOTSTRAP_RUNTIME_OBJECTS) \
		$(RUNTIME_SYSCALLS_OBJECT)
