# -----------------------------------------------------------------------------
# Bootstrap userspace
# -----------------------------------------------------------------------------

USER_BOOTSTRAP_BUILD_DIR := $(BUILD_DIR)/user-bootstrap

USER_BOOTSTRAP_LINKER_SCRIPT := user/bootstrap/user.ld

USER_BOOTSTRAP_CRT0_SOURCE := user/runtime/crt0.S
USER_BOOTSTRAP_CRT0_OBJECT := $(USER_BOOTSTRAP_BUILD_DIR)/crt0.o

USER_BOOTSTRAP_SYSCALL_SOURCE := user/runtime/syscall.S
USER_BOOTSTRAP_SYSCALL_HEADER := user/runtime/syscall.h
USER_BOOTSTRAP_SYSCALL_OBJECT := $(USER_BOOTSTRAP_BUILD_DIR)/syscall.o

USER_BOOTSTRAP_EXIT_SOURCE := user/runtime/exit.c
USER_BOOTSTRAP_EXIT_OBJECT := $(USER_BOOTSTRAP_BUILD_DIR)/exit.o

USER_SYSCALL_ABI_HEADER := include/myos/abi/syscall.h
USER_RUNTIME_INCLUDE_DIR := user/runtime/include

USER_BOOTSTRAP_STRING_SOURCE := user/runtime/string.c
USER_BOOTSTRAP_STRING_HEADER := user/runtime/include/string.h
USER_BOOTSTRAP_STRING_OBJECT := $(USER_BOOTSTRAP_BUILD_DIR)/string.o

USER_BOOTSTRAP_MALLOC_SOURCE := user/runtime/malloc.c
USER_BOOTSTRAP_STDLIB_HEADER := user/runtime/include/stdlib.h
USER_BOOTSTRAP_MALLOC_OBJECT := $(USER_BOOTSTRAP_BUILD_DIR)/malloc.o

USER_BOOTSTRAP_FORMAT_SOURCE := user/runtime/format.c
USER_BOOTSTRAP_FORMAT_HEADER := user/runtime/format.h
USER_BOOTSTRAP_FORMAT_OBJECT := $(USER_BOOTSTRAP_BUILD_DIR)/format.o

USER_BOOTSTRAP_STDIO_SOURCE := user/runtime/stdio.c
USER_BOOTSTRAP_STDIO_HEADER := user/runtime/include/stdio.h
USER_BOOTSTRAP_STDIO_OBJECT := $(USER_BOOTSTRAP_BUILD_DIR)/stdio.o

USER_BOOTSTRAP_PROCESS_SOURCE := user/runtime/process.c
USER_BOOTSTRAP_PROCESS_HEADER := user/runtime/include/myos/process.h
USER_BOOTSTRAP_PROCESS_OBJECT := $(USER_BOOTSTRAP_BUILD_DIR)/process.o

USER_BOOTSTRAP_FILE_SOURCE := user/runtime/file.c
USER_BOOTSTRAP_FILE_HEADER := user/runtime/include/myos/file.h
USER_BOOTSTRAP_FILE_OBJECT := $(USER_BOOTSTRAP_BUILD_DIR)/file.o

USER_BOOTSTRAP_RUNTIME_OBJECTS := \
	$(USER_BOOTSTRAP_CRT0_OBJECT) \
	$(USER_BOOTSTRAP_SYSCALL_OBJECT) \
	$(USER_BOOTSTRAP_EXIT_OBJECT) \
	$(USER_BOOTSTRAP_STRING_OBJECT) \
	$(USER_BOOTSTRAP_MALLOC_OBJECT) \
	$(USER_BOOTSTRAP_FORMAT_OBJECT) \
	$(USER_BOOTSTRAP_STDIO_OBJECT) \
	$(USER_BOOTSTRAP_PROCESS_OBJECT) \
	$(USER_BOOTSTRAP_FILE_OBJECT)

USER_INIT_SOURCE := user/bootstrap/init/main.c
USER_INIT_OBJECT := $(USER_BOOTSTRAP_BUILD_DIR)/init.o
USER_INIT_ELF    := $(USER_BOOTSTRAP_BUILD_DIR)/init.elf

USER_BOOTSTRAP_CFLAGS := \
	--target=$(TARGET) \
	-ffreestanding \
	-fno-stack-protector \
	-fno-common \
	-fno-pic \
	-fno-pie \
	-mno-red-zone \
	-mgeneral-regs-only \
	-O0 \
	-g \
	-I$(MYOS_INCLUDE_DIR) \
	-I$(USER_RUNTIME_INCLUDE_DIR) \
	-fno-builtin \
	-Wall \
	-Wextra \
	-Werror \
	-Wpedantic

$(USER_BOOTSTRAP_BUILD_DIR):
	mkdir -p $(USER_BOOTSTRAP_BUILD_DIR)

$(USER_BOOTSTRAP_STRING_OBJECT): \
	$(USER_BOOTSTRAP_STRING_SOURCE) \
	$(USER_BOOTSTRAP_STRING_HEADER) \
	| $(USER_BOOTSTRAP_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(USER_BOOTSTRAP_MALLOC_OBJECT): \
	$(USER_BOOTSTRAP_MALLOC_SOURCE) \
	$(USER_BOOTSTRAP_STDLIB_HEADER) \
	$(USER_BOOTSTRAP_STRING_HEADER) \
	| $(USER_BOOTSTRAP_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(USER_BOOTSTRAP_FORMAT_OBJECT): \
	$(USER_BOOTSTRAP_FORMAT_SOURCE) \
	$(USER_BOOTSTRAP_FORMAT_HEADER) \
	$(USER_BOOTSTRAP_STRING_HEADER) \
	| $(USER_BOOTSTRAP_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(USER_BOOTSTRAP_STDIO_OBJECT): \
	$(USER_BOOTSTRAP_STDIO_SOURCE) \
	$(USER_BOOTSTRAP_STDIO_HEADER) \
	$(USER_BOOTSTRAP_FORMAT_HEADER) \
	| $(USER_BOOTSTRAP_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(USER_BOOTSTRAP_PROCESS_OBJECT): \
	$(USER_BOOTSTRAP_PROCESS_SOURCE) \
	$(USER_BOOTSTRAP_PROCESS_HEADER) \
	$(USER_BOOTSTRAP_SYSCALL_HEADER) \
	$(USER_SYSCALL_ABI_HEADER) \
	| $(USER_BOOTSTRAP_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(USER_BOOTSTRAP_FILE_OBJECT): \
	$(USER_BOOTSTRAP_FILE_SOURCE) \
	$(USER_BOOTSTRAP_FILE_HEADER) \
	$(USER_BOOTSTRAP_SYSCALL_HEADER) \
	$(USER_SYSCALL_ABI_HEADER) \
	| $(USER_BOOTSTRAP_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(USER_BOOTSTRAP_CRT0_OBJECT): \
	$(USER_BOOTSTRAP_CRT0_SOURCE) \
	| $(USER_BOOTSTRAP_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(USER_BOOTSTRAP_SYSCALL_OBJECT): \
	$(USER_BOOTSTRAP_SYSCALL_SOURCE) \
	| $(USER_BOOTSTRAP_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(USER_BOOTSTRAP_EXIT_OBJECT): \
	$(USER_BOOTSTRAP_EXIT_SOURCE) \
	$(USER_BOOTSTRAP_SYSCALL_HEADER) \
	$(USER_SYSCALL_ABI_HEADER) \
	| $(USER_BOOTSTRAP_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(USER_INIT_OBJECT): \
	$(USER_INIT_SOURCE) \
	| $(USER_BOOTSTRAP_BUILD_DIR)
	$(CLANG) $(USER_BOOTSTRAP_CFLAGS) \
		-c $< \
		-o $@

$(USER_INIT_ELF): \
	$(USER_BOOTSTRAP_RUNTIME_OBJECTS) \
	$(USER_INIT_OBJECT) \
	$(USER_BOOTSTRAP_LINKER_SCRIPT)
	$(LD_LLD) \
		-static \
		--build-id=none \
		-T $(USER_BOOTSTRAP_LINKER_SCRIPT) \
		-o $@ \
		$(USER_BOOTSTRAP_RUNTIME_OBJECTS) \
		$(USER_INIT_OBJECT)
